### ISSUE TITLE
Send Bulk Push to multiple devices 

### ISSUE THREAD

**Issue by salim-buet03** [web-push-libs/pywebpush#140]
Sorry, It's a question not a bug report :) 

In web-push-php, there is e bulk method to send pushes to multiple devices at a time. 
`$webPush->queueNotification`
and then 
`$webPush->flush()`

is there any similar method in pywebpush?

**Comment by jrconlin** [comment]
No, partly because it'd be easier for folk to build their own.

There are a few different threading engines out there, and if I were to pick one, it might limit a developers ability to use the library. I've gotten burned quite a few times in the past by "helpful" libraries making functions like that, but then forcing me to alter my applications design or dependencies in order to fit their needs.

Instead, I tried to make the library reasonably thread friendly (allowing you to either share a common `WebPusher` or by building your own queue and divvying up load to multiple instances).

**Comment by salim-buet03** [comment]
great thanks, I am closing it :)
