### ISSUE TITLE
PushManager.subscribe() needs applicatonServerKey option.

### ISSUE THREAD

**Issue by flagboy** [web-push-libs/pywebpush#15]
Please check the following links:
https://tools.ietf.org/html/draft-thomson-webpush-vapid-02#page-6
https://developer.mozilla.org/en-US/docs/Web/API/PushManager/subscribe

I believe  option is necessary to send encrypted messages.

The server key is currently used for WebPusher.encode()

[The comment](https://github.com/web-push-libs/pywebpush/blob/master/pywebpush/__init__.py#L126) says

```

The server key is an ephemeral ECDH key used only for this transaction

```

However, I believe this key is not only for this transaction but also for the subscribe method.

**Comment by jrconlin** [comment]
I believe the confusion is because there's two different ECDH keys at play.

One key is used by VAPID, and doesn't really figure into WebPush encryption. The other is used internally as part of the ECDH process. The comment you note points to the WebPush encryption ECDH key, which is indeed ephemeral for the given transaction. (ECDH is a fun way to melt your brain and convince yourself that math is broken.)

The ECDH used by VAPID is set by the DOM endpoint request. The public key is handed to the UserAgent, which can pass it to the Push Service in order to "lock" a given endpoint to a VAPID signature. You'll need to make sure that any future Subscription Updates are properly signed with the private half of the VAPID key. (See https://github.com/web-push-libs/vapid/tree/master/python  if you want an example library for doing that.)

VAPID is optional. (Heck, "Voluntary" is the "V" in VAPID) so WebPush doesn't really need to know anything about it. 

Does that help?

(Also, sorry about the delay)

**Comment by flagboy** [comment]
Thank you for your reply.
It was very helpful.
If it did not work out, also Can I ask you a question?

**Comment by jrconlin** [comment]
Absolutely you can ask questions. 

And for the record some quick answers:
cheetah 
~5.39116(13) *10^-44 
and of course
42

**Comment by flagboy** [comment]
`registration.pushManager.subscribe()` returns `PushSubscription` object.
The object contains a endpoint, but not keys in FireFox.

I could get the `p256dh` key by calling `PushSubscription.getKey('p256dh')`.
However, I could not figure out how I could retrieve auth key.

Do you have any idea?

**Comment by jrconlin** [comment]
Yep. if you look at the docs for [PushSubscription](https://developer.mozilla.org/en-US/docs/Web/API/PushSubscription), you'll see a method called [.toJSON()](https://developer.mozilla.org/en-US/docs/Web/API/PushSubscription/toJSON). This returns a structure that has all of the data you'll need. 

I see that in the comments I've mistakenly said it was .getJSON(). I'll fix that.

**Comment by flagboy** [comment]
I called [PushSubscription](https://developer.mozilla.org/en-US/docs/Web/API/PushSubscription).[toJSON()](https://developer.mozilla.org/en-US/docs/Web/API/PushSubscription/toJSON). 
That returns ` Object { endpoint: "https://updates.push.services.mozil…" } ` , keys does not contain.

I did not know the incorrect comments about .getJSON.

**Comment by jrconlin** [comment]
It may well be that the version of Firefox you're testing doesn't support WebPush data. If I remember correctly, version 48+ supports data encryption. Earlier versions either didn't support it, or only partially supported it due to the moving specification.

Some older versions also supported calling .getKey('auth') and .getKey('p256dh').

Obviously, with Chrome and Edge, things are going to slightly different as they're rolling out data encryption on their schedule. The .toJSON() call is the preferred method, and browsers that support WebPush will support that call.

**Comment by flagboy** [comment]
I’m sorry that the version I tested was 44.
However, I could not call `.getKey('auth')` with version 48 as well as 44.
(If you have any idea, please let me know. If not, it’s ok! You’ve been very kind already)

I was mistaken that `pywebpush` can be used for the case of not sending data for old browsers, but it seems not.

Thank you very much for answering many questions of mine!!

**Comment by jrconlin** [comment]
Sorry, got pulled into a few things. You should be able to call subscription`.getKey('auth')` from the push subscription object returned by `registration.pushManager.subscribe()`. If it's any help, you can look at what I do in the [Web Push Data Test Page](https://github.com/mozilla-services/WebPushDataTestPage/blob/gh-pages/index.html#L434). I'll also be honest, I've not really checked if I'm being smart about how I do things in pywebpush if you're not sending data. Mostly because not sending data is a LOT easier. You just do a POST to the endpoint you've gotten. No worries about the weird headers, no encryption dance. Heck, you don't even need to get the various keys from the subscription. All you need to do is pass the VAPID info (if you want, again, not needed) and a `TTL` (Time To Live for the notification). [I've got a write up](https://blog.mozilla.org/services/2016/08/23/sending-vapid-identified-webpush-notifications-via-mozillas-push-service/#send_nodata) that describes a lot of this (probably in WAY more detail than most folks want) That link drops you off into the "Send A Push Notification With No Data" bit.

**Comment by jpjitendrapal** [comment]
to get object data from subscription you can use: JSON.parse(JSON.stringify(subscription))
