### ISSUE TITLE
Exception Occured when Sending Web Push: Unsupported elliptic curve signature algorithm (iOS Safari)

### ISSUE THREAD

**Issue by AmmarKhawaja** [web-push-libs/pywebpush#173]
I am getting this exception when attempting to send a push notification **specifically to iOS devices with Safari**:

`Unsupported elliptic curve signature algorithm`

However, web push notifications work perfectly with Safari and Chrome on my laptop. Something weird is that iOS Safari notifications have previously been sent a few times but then stopped working. I have not been able to have them sent today at all.

This is my function for sending a push notification, the exception block is triggered here.
(VAPID_PRIVATE_KEY is the private key in PEM format.)

```
def send_push(user_not='', title='xxx', url='https://www.xxx.com/'):
    try:
        webpush(subscription_info=user_not, data=json.dumps({
            'title': title,
            'body': url,
            'icon': 'xxx',
            }),
            vapid_private_key=VAPID_PRIVATE_KEY, 
            vapid_claims={'sub': 'mailto:xxx@gmail.com'}
            )
    except Exception as e:
        with open(file_prefix + 'error_log.txt', 'a', encoding='utf-8') as t:
            t.write('WEBPUSH: Exception Occured when Sending Web Push')
            t.write(str(e) + '\n')
```

I could understand if I am using the wrong private key format if it was not working at all, but it is working for Chrome and Safari on my computer. Do I need to have it passed through another way?

**Comment by jrconlin** [comment]
Huh.

So, if I understand correctly, you're composing an outbound push message on your system, presumably a Mac. 
The push works for sending to your local Chrome and Safari install, but is failing when you try to send it to iOS.

What I'm unclear about is what is raising the `Exception("Unsupported elliptic curve signature algorithm")`
I'm not sure if it's happening when the VAPID key is being use to generate the Auth header, or if this is happening at some other point. (I don't think Apple is rejecting it since the error would be completely different)

Would it be possible to see if you could send the message using the command line tool and include the `--verbose` flag (or include the `verbose=True` option in the `webpush` call.  I don't need to see the output, but it would be interesting to see how far it gets before it fails.

(And yeah, I really need to fix the logging for this library. Sorry.) 

If you enable `--verbose` mode,

**Comment by AmmarKhawaja** [comment]
The outbound push message is sent from a PythonAnywhere server, I use them to host everything. But yes everything else is accurate.

If the error is not coming from Apple then I guess the only other difference is the endpoint, so maybe something there?

Anyways, I didn't know there was a command line tool.. will try it out and let you know of the output!

**Comment by AmmarKhawaja** [comment]
Back with an update, this is the command I ran:

```
python3 -m pywebpush
--data message.txt
--info subscription.json
--key XXX
--claims vapid_claims.json
--verbose
```

Response:
`<Response [201]>`

Tried refreshing the subscription endpoint and got the same response. So from here it looks like everything is working correctly.

**Comment by AmmarKhawaja** [comment]
Ok doing that test inspired me to fiddle around with my webpush parameters a bit and see if that was the issue, and I found something VERY weird.

If I modify any webpush parameter, whether that be deleting the icon field, or deleting a letter in vapid_claims.sub, it sends a notification, but only ONCE, subsequent requests fail. If I want to send another notification, I can do so by doing any modification again, and it will send successfully.

Im going to do some more testing but so far this is what I've deducted.

**Comment by jrconlin** [comment]
Huh, so things are working if you use the CLI, but not if you use the code in the library? That is odd.
(The CLI basically does what you're doing, only with some extra wrapping.)

Apple's push is also a little... odd. (Like the requirement that you have to show the notification to the user.) I wonder if they might be doing some caching on their server, so you might need to add a `nonce={randomValue}` to your payload to break the cache? I'm guessing they probably don't want rogue sites spamming notifications to devices or something.

The VAPID header stuff _shouldn't_ matter? Since the idea there is that you have One VAPID header that you could technically re-use for a day. (VAPID headers are supposed to be good for 24 hours.) It's cheap enough to make new ones, though. 

It's funny that they might be including the `Authentication:` header as part of the "uniqueness", but 🤷🏻. Apple is just as inscrutable to us as they are to you.

**Comment by AmmarKhawaja** [comment]
Well off the top of my head, the Authentication header is the only thing that discerns between different senders. But yes it's pretty weird that they may not allow duplicate notifications, if that is the reason for this error. Now instead of sending 1001 notifications per minute, spammers can only send 1000 per minute.. it doesn't add up.

**Comment by jrconlin** [comment]
Heh, I can speak from direct personal experience that spammers are exceptionally good at ignoring any minor hurdles you put in front of them. 

That said, THANK YOU for helping figure out what's going on here. Hopefully it also helps out others.
