### ISSUE TITLE
Please add ttl to webpush function.

### ISSUE THREAD

**Issue by ondrejj** [web-push-libs/pywebpush#85]
Please add ttl option to webpush function. It's too complicated to call WebPusher.
webpush function is great, but if I need to set TTL, then I can't use it.
Thank you.

**Comment by jrconlin** [comment]
Not to sound like a jerk, but calling the "long form" of 
``` result = webpush(subscription_info, data) ```
is
```result = Webpusher(subscription_info).send(data) ```

`webpush()` also shortcuts the VAPID stuff, but if you're not just calling `webpush()` for one or two calls, I really hope you're caching the `vapid_headers` information. Otherwise you're paying for CPU you don't need to.  

I really hoped that wouldn't be terribly complicated. I'd love to know what part you struggled with. 

Since I need to check library revisions, I'll add the `ttl=` var to `webpush()`

**Comment by ondrejj** [comment]
I am calling webpush just for some calls, mostly only once per day, so I don't cache vapid_headers.
This way this vapid stuff is a bit complicated in my script. May be it would be better to integrate these
wapid things into Webpusher object or at least create a function, which helps with vapid.

Thank you for adding ttl= to webpush. :-)

**Comment by jrconlin** [comment]
Fair enough. I'd prefer to keep the Vapid stuff and the webpush stuff separate as much as possible* for a lot of reasons, but thanks for the feedback!

*mostly because the Vapid stuff has a LOT of customization potential I'd prefer not to have to add to pywebpush

**Comment by ondrejj** [comment]
Then it can be useful to have whole if vapid_claims ... in separate function.

Thank you for releasing version 1.6.0. I already built Fedora rpm's to my repo and tested it. Works well. :-)
