### ISSUE TITLE
When using the WebPusher object, use a dedicated function to change its subscription_info

### ISSUE THREAD

**Issue by Seanjimon** [web-push-libs/pywebpush#93]
*Use case*
I'm using this lib and especially the WebPusher object to send Vapid Web Push.
Why don't I use the webpush function ? Because my app can use the same WebPusher instance throughout its entire lifetime. That is why, for optimisation reason, I prefer using the same requests.Session() object each time I need WebPush.
The issue is that the subscription_info changes almost every time but I don't want to instanciate a new WebPusher;

*Current workaround*
in my wrapper, I have this method :
```
    def _update_subscription_info(self, subscription_info):
        # Here we naively copy the operations linked to subscription_info
        # from WebPusher.__init__()
        # aka validate subscription_info and store keys
        # Mandatory because subscription_info keeps changing
        if 'endpoint' not in subscription_info:
            raise WebPushException(
                "subscription_info missing endpoint URL"
            )
        self.webpusher.subscription_info = deepcopy(subscription_info)
        self.webpusher.auth_key = self.webpusher.receiver_key = None
        if 'keys' in subscription_info:
            keys = self.webpusher.subscription_info['keys']
            for k in ['p256dh', 'auth']:
                if keys.get(k) is None:
                    raise WebPushException(
                        "Missing keys value: {}".format(k))
                if isinstance(keys[k], six.string_types):
                    keys[k] = bytes(keys[k].encode('utf8'))
            receiver_raw = base64.urlsafe_b64decode(
                self.webpusher._repad(keys['p256dh']))
            if len(receiver_raw) != 65 and receiver_raw[0] != "\x04":
                raise WebPushException("Invalid p256dh key specified")
            self.webpusher.receiver_key = receiver_raw
            self.webpusher.auth_key = base64.urlsafe_b64decode(
                self.webpusher._repad(keys['auth']))
```
which is quite a dirty hack as it's just a copy/paste.

*Question*
Would you implement such a method in a more graceful way directly in the WebPusher, in order to simply be able to do a `my_web_pusher.update_subscription_info(subscription_info)` ?

If needed, I could spend a bit of time to suggest a PR.

**Comment by jrconlin** [comment]
I guess I'm not quite sure why hanging onto the webpush instance is a good thing. I can very much understand wanting to keep the same VAPID info and subscription info, but the webpush instance just does some simple checks and wraps a call to requests. The actual webpush bit is kinda disposable.

The "stand alone" function basically just does that. I'll admit I'm not super happy about the `deepcopy()`, but that's more a problem with Python wanting to use references and having to modify things for formatting. If you keep subscription info external, it's overkill, but a few apps don't do that for whatever reasons, and it's bad form for a library to muck with things. 

Yeah, there's also some GC costs, but I don't think those are horrible. Please let me know if it's otherwise. 

From what it sounds like, I'd probably just put the `webpush(subscription_info,... )` call in it's own thread and treat it as opaque and disposable.  

If you've got good profiling info, I'm happy to hear it and see what can be improved.

**Comment by Seanjimon** [comment]
Thanks for your quick reply !
Indeed, the only thing I really need in my particular case to improve performance is to keep the request.Session which has not direct link with this library. You are 200% right, this issue must be closed !
